services:
  mysql:
    build: docker/mysql
    ports:
      - 3306:3306
    volumes:
      - ./sql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=django
    healthcheck:
      test: "exit 0"

  mongo:
    build: docker/mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
  rabbitmq:
    build:
      context: docker/rabbitmq
      dockerfile: Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      timeout: 5s
      retries: 1



  python:
    build: ./docker/python
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html

  web:
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    working_dir: /etc/nginx
    depends_on:
      - python

