services:
  mysql:
    build: docker/mysql
    ports:
      - 3306:3306
    volumes:
      - ./sql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=django
    healthcheck:
      test: "exit 0"
  rabbitmq:
    build:
      context: docker/rabbitmq
      dockerfile: Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 10

  web:
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    working_dir: /etc/nginx
    depends_on:
      - python

  python:
    build: ./docker/python
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

